#!/usr/bin/env bash

CBUILD_ROOT="$(cd "$(dirname "$0")" && pwd)"
CMD_DIR="$CBUILD_ROOT/cmd"
LIB_DIR="$CBUILD_ROOT/lib"

source "$LIB_DIR/config.sh"
source "$LIB_DIR/common.sh"

cmd="$1"

case "$cmd" in
    init)
        source "$CMD_DIR/init.sh"
        ;;
    build)
        source "$CMD_DIR/build.sh"
        ;;
    run)
        source "$CMD_DIR/run.sh"
        ;;
    clean)
        source "$CMD_DIR/clean.sh"
        ;;
    rebuild)
        source "$CMD_DIR/rebuild.sh"
        ;;
    info)
        source "$CMD_DIR/info.sh"
        ;;
    *)
        throw_error 3
        ;;
esac
