#!/usr/bin/env bash

SCOPE="help"

echo "cbuild is a tool for building, running and managing C projects."
echo
echo "Usage:"
echo "  cbuild <command> [options]"
echo
echo "Commands:"
echo "  init"
echo "      Initialize a new C project in the current directory."
echo "      Creates a cbuild.conf configuration file."
echo
echo "  build"
echo "      Build the project."
echo "      Compiles source files into object files and links them"
echo "      into the configured executable."
echo "      Only files that need to be rebuilt are compiled."
echo
echo "  run"
echo "      Build and run the project."
echo "      If the project is not up to date, it is built before execution."
echo
echo "  clean"
echo "      Remove build artifacts generated by cbuild."
echo "      Source files and project configuration are not affected."
echo
echo "  rebuild"
echo "      Perform a clean build of the project."
echo "      Equivalent to running 'clean' followed by 'build'."
echo
echo "  info"
echo "      Display information about the current project and its configuration."
echo
echo "  help"
echo "      Display this help message."
echo
echo "Options:"
echo "  -v, --verbose"
echo "      Display additional information about the build process,"
echo "      including commands executed by cbuild."
echo
echo "  -d, --debug"
echo "      Enable debug output with detailed information about"
echo "      cbuild's internal operations."
echo
echo "  -h, --help"
echo "      Display this help message."
echo
echo "Examples:"
echo "  cbuild init"
echo "      Initialize a new project."
echo
echo "  cbuild build"
echo "      Build the current project."
echo
echo "  cbuild build --verbose"
echo "      Build the project and display the commands being executed."
echo
echo "  cbuild run"
echo "      Build and run the project."
echo
echo "  cbuild clean"
echo "      Remove generated build files."
echo
echo "For more information, see the cbuild documentation."
